import ModeToggle from '@/components/theme/ModeToggle'
import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
// import { Inter } from 'next/font/google'
// import './globals.css'
import Image from 'next/image'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        {/* login layourt */}
      <body>
        <div className="grid md:grid-cols-2">
          
          <div className="col-span-1 relative">
          <Image src="/../../static/image/3.png" alt="me" fill={true} />
          </div>

          
          <div className="grid h-screen px-6 items-center">
            <div className="absolute right-0 top-0">
              <div className="p-6">
                <ModeToggle/>
              </div>
            </div>
          {children}
          </div>
        </div>
      </body>
    </html>
  )
}
